name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

permissions:
  pull-requests: read
  statuses: write

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        with:
            wip: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}